### PR TITLE
Add introduction and license to readme

### LINKED ISSUE #1: Write a paragraph on the purpose of the project in the README
The readme should at the minimum contain a short description of the repository.

### PR DESCRIPTION
**Pull request by haavardnk**
Closes #1

### CODE REVIEW

**Review by markusdregi — APPROVED** [review]
Looks good to me 👍

**Comment by markusdregi** [comment]
The README looks good 👍 But I encourage you to read the following post on commit messages: https://chris.beams.io/posts/git-commit/. That is at least the standard we follow in our team ;)

**Comment by haavardnk** [comment]
Commit message changed, check if OK

**Comment by haavardnk** [comment]
Added some badges to the readme aswell.

**Review by markusdregi — APPROVED** [review]
Looks good 👍

**Pull request merged**
